### ISSUE TITLE
 http://sicphaskell is an 404 link

### ISSUE THREAD

**Issue by MarisaKirisame** [chris-taylor/SICP-in-Haskell#1]

**Comment by chris-taylor** [comment]
Sorry, what?

**Comment by MarisaKirisame** [comment]
![capture](https://cloud.githubusercontent.com/assets/3397377/12888515/733544ba-ce2f-11e5-8d4d-b068270b521a.PNG)

I think that link is not working

**Comment by chris-taylor** [comment]
Thanks, fixed.
